# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-22 00:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('codingtool', '0002_auto_20170121_1600'),
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='code',
            name='notation',
        ),
        migrations.AddField(
            model_name='membership',
            name='code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codingtool.Code'),
        ),
        migrations.AddField(
            model_name='membership',
            name='notation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codingtool.Notation'),
        ),
        migrations.AddField(
            model_name='code',
            name='notations',
            field=models.ManyToManyField(through='codingtool.Membership', to='codingtool.Notation'),
        ),
    ]
